services:
  db:
    image: mariadb:11.4
    container_name: my-mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER:?MARIADB_USER não configurado}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:?MARIADB_PASSWORD não configurado}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-${MARIADB_DB:?MARIADB_DATABASE ou MARIADB_DB não configurado}}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-${MARIADB_PASSWORD:?MARIADB_PASSWORD não configurado}}
    volumes:
      - "./mariadb-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      db:
        condition: service_healthy